### ISSUE TITLE
sum of elevation differences

### ISSUE THREAD

**Issue by wbeisser** [tboegi/GpsMaster#9]
hi, 

first of all thank you for this brilliant piece of software.

i just discovered the "correct elevation" function which adds the elevation to all route points. this enables you to view the elevation chart to analyse the elevation profile of your route.

to estimate the duration of a planned hiking trip, you need the sum of all ascending differences and the sum of all descending. it would be great, if these two values would be shown next to the min/max elevations in the property segment of the route.

by the way, there are the hikebikemap and the opentopomap that would make great additions to the selectable maps.

cheers,
wb

**Comment by rfuegen** [comment]
you're welcome ;-) and thanks for the suggestions.

1) I just added hikebikemap & opentopomap tilesources to GpsMaster. they will be included in the next release. until then, check here on how to add them via config file:
[https://wiki.openstreetmap.org/wiki/GpsMaster/Documentation/TileSources](https://wiki.openstreetmap.org/wiki/GpsMaster/Documentation/TileSources)

2) I'm considering the suggested elevation differences for implementation in a future version. Before that, I need to come up with a kind of "folding" feature in the properties panel, since there'd be to much rows for smaller screens.

**Comment by wbeisser** [comment]
perfect, thank you.
1. the hikebikemap does not work like discribed in your link. the topomap is great :-)
2. i don't know if this would crash the concept, but maybe even the complete formula to estimate the duration of the route would be helpful for many. in the meantime i have made a little tool to do that. it can analyse the output gpx file and calculate the estemated time for a hike.
[https://www.andeansummitadventure.rocks/hiking-time-calculations/](url)

**Comment by tboegi** [comment]
The latest jar file is found here:
(Including the 2 new map providers)
Happy testing!

https://github.com/tboegi/GpsMaster/releases/tag/v0.63.38-rc0

**Comment by wbeisser** [comment]
both new maps work great with this new version, thanks.

**Comment by wbeisser** [comment]
i've sneaked a calculation for the estimated hiking time (in hours according to official formula for hiking routes) into [the  insert and move waypoints](https://github.com/tboegi/GpsMaster/pull/14) pull request. it is stored as estHikeHours in routes. if it changes (due to editing route points or refreshing elevation data), it will system out the value (h:mm).

for me this issue is done. please feel free to add the estimated hike time to the route property panel whenever there is space for it. 

wb
